### PR TITLE
very not so simple update

### PR DESCRIPTION
**Pull request by YumYummity**
auto-get latest roblox version, auto-replace all versions if multiple versions (due to roblox installer bug), warn if roblox not up to date, tell user they need to update every time roblox updates, list all versions replaced

### CODE REVIEW

**Comment by YumYummity** [comment]
most of this code came from my Advanced-RobloxOOF repository lol.

**Comment by ColdCawfee** [comment]
i never stole any code from any repo

**Comment by ColdCawfee** [comment]
that is my next item of business and is being worked on

**Comment by YumYummity** [comment]
Ok, well GL!

**Comment by YumYummity** [comment]
Just saying, your current code does not support multiple versions due to glitched installer (like 25% of users have this). The first directory IS NOT always the latest.

**Pull request closed without merging**
